### ISSUE TITLE
command aws boto3 quick start resulted in an error path should be a path.relative()

### ISSUE THREAD

**Issue by felipe1982** [vemel/boto3-ide#2]
This extension is actually very powerful! It helps me to show the function/method signatures which make my boto3 development faster and easier! Thank you.

![image](https://user-images.githubusercontent.com/275621/150039313-008bb9f7-0ee4-44bb-842a-641a9be394a5.png)

I get an error when I have already installed and configured all required components, and I try to install them again, selecting "install" instead of "modify" or "upgrade"

**OS** Windows 10 with WSL2 openSUSE Leap 15.2
**VScode** Latest stable
**Exention Version** Latest Stable
**Python** 3.6.15
**pipenv**  version 2022.1.8
**pip** 21.3.1

**Comment by vemel** [comment]
Hello! Thank you for the report and sorry for late response. I have not tested it thoroughly on Windows and there could be issues with path building. I am going to test it tomorrow. You use remote WSL for development, right?

**Comment by felipe1982** [comment]
Yes I use wsl2

**OS** Windows 10 with WSL2 openSUSE Leap 15.2

**Comment by vemel** [comment]
I found an issue, this is actually `ignore` library that throws a hard error if it cannot find a relative path. I will just skip files in this case because they are outside of a project root. Added a fix, should be released today.

**Comment by vemel** [comment]
Please let me know if the new version works for you.

**Comment by felipe1982** [comment]
It appears to work, close this, and I'll open again if it returns. :)
