### ISSUE TITLE
Often does not detect pipenv, defaults to pip

### ISSUE THREAD

**Issue by felipe1982** [vemel/boto3-ide#3]
I use pipenv in my environment, and often Boto3-ide does not pick it up, instead defaulting to pip. I have set my default interpreter to use my pipenv environment, and reloaded VSCode, but this problem remains.

![image](https://user-images.githubusercontent.com/275621/151293538-78c3ac96-22fa-442e-ab16-3c4f69dfc9fb.png)
![image](https://user-images.githubusercontent.com/275621/151293581-f0d5b8b4-6577-4615-9ea5-e78e0fbb78a2.png)

**Comment by felipe1982** [comment]
I have many workspaces (... Or folders or repositories) open in 1 single vscode window. Some have Pipfile.lock but no guarantee all do.

**Comment by vemel** [comment]
I take into account only the first workspace. I should check how python extension finds an active workspace

**Comment by vemel** [comment]
I have just added support for multiple directories in one workspace. Now `pipenv`/`poetry` should be available if any of the directories have a lock file. Also, this directory will be chosen as a `workDir` (so, the installer changes the working directory to the one with a lock file before installing packages). For now, it is not possible to choose work dir if you have multiple lock files, the first one is selected.

**Comment by vemel** [comment]
Please let me know if this solution works for you.

**Comment by felipe1982** [comment]
It appears to work, close this, and I'll open again if it returns. :)
