### ISSUE TITLE
intellisense doesnt seem to work

### ISSUE THREAD

**Issue by DesAWSume** [vemel/boto3-ide#4]
Issue: intellisense seem to work

DES: after installed the extension in VScode, 

Env: Python 3.10

pylance and intellisense are installed

**Comment by Amin-Mashayekhan** [comment]
Hi
go to the vscode setting, on user tab > Extensions. select the link that related to the intellisense extension, change some options and observe the result.

**Comment by DesAWSume** [comment]
Hi Amin

Thanks for this, it won't appear in settings -> extension 

it just not appears at all
<img width="441" alt="image" src="https://user-images.githubusercontent.com/7110636/152674624-764fc571-94e9-4c5e-99ea-df4536f93c5c.png">

**Comment by DesAWSume** [comment]
Hey Amin
Thanks for the reply, I compared mine with other PC Vscode settings, I couldnt find what is the cause,
It is just not able to show the anything

**Comment by vemel** [comment]
Hello @DesAWSume ,

THis is strange that you do not have IntelliSense even for unknown type, so please check the following:

- Make sure `Python` and `Pylance` VSCode extensions are installed
- `Pylance` is selected as a Python Language Server in VSCode settings
- Run `AWS boto3: Quick Start` command in VSCode (Ctrl+Shift+P) and install `boto3-stubs`

Now you should have type checking and IntelliSense. Please let me know if it works for you or if you have any issues with the process.

**Comment by DesAWSume** [comment]
Hi Vemel

Work like a GEM, awesome!!!! Love your work!!!
Thanks heaps

**Comment by vemel** [comment]
You are welcome! Let me know if anything else comes up.
